development:
  adapter: postgresql
  encoding: unicode
  database: daykoozie_api_development
  pool: 5
  host: localhost
  username: <%= ENV['USER'] %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: daykoozie_api_test
  host: localhost
  pool: 5
  username: <%= ENV['USER'] %>
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: daykoozie_api_production
  host: 127.0.0.1
  pool: 5
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASSWORD'] %>
